apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msr-ingress
  namespace: swag-intg
spec:
  ingressClassName: class
  rules:
  - host: msr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: msr-k8ssvc
            port:
              number: 5555