apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-ingress
  namespace: default
subjects:
- kind: User
  name: "docker-desktop"  # replace with the correct username or service account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ingress-reader
  apiGroup: rbac.authorization.k8s.io
