apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: msr-k8ssvc
  namespace: swag-intg
spec:
  selector:
    app: msr-k8s
  ports:
    - protocol: "TCP"
      port: 5555 # The port that the service is running on in the cluster
      targetPort: 5555 # The port exposed by the service
    - protocol: "TCP"
      port: 6666 # The port that the service is running on in the cluster
      targetPort: 6666 # The port exposed by the service
    - protocol: "TCP"
      port: 7777 # The port that the service is running on in the cluster
      targetPort: 7777 # The port exposed by the service
  type: NodePort # type of the service.